name: Deploy Bicep files

trigger: none
# - main

variables:
  resourceGroupName: 'rg-bicep-demo-0017'
  location: 'westeurope'
  webAppName: 'bicep0017'
  templateFile: '01-bicep-webapp/webapp-linux.bicep'

pool:
  vmImage: 'ubuntu-latest'

steps:

- task: AzureCLI@2
  displayName: Check and Delete Existing Web App if Exists
  inputs:
    azureSubscription: 'Free Trial(abdc1047-6e87-4b5a-80a0-c91483bc5655)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      existingApp=$(az webapp show --resource-group $(resourceGroupName) --name $(webAppName) --query name --output tsv)
      if [ "$existingApp" == "$(webAppName)" ]; then
        echo "Web app $(webAppName) exists. Deleting..."
        az webapp delete --resource-group $(resourceGroupName) --name $(webAppName)
      else
        echo "Web app $(webAppName) does not exist."
      fi

- task: AzureCLI@2
  displayName: Preview Bicep Changes
  inputs:
    azureSubscription: 'Free Trial(abdc1047-6e87-4b5a-80a0-c91483bc5655)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az --version
      az group create --name $(resourceGroupName) --location $(location)
      az deployment group what-if --resource-group $(resourceGroupName) \
         --template-file $(templateFile) \
         --parameters webAppName=$(webAppName)

- task: AzureCLI@2
  displayName: Deploy Bicep To Azure
  inputs:
    azureSubscription: 'Free Trial(abdc1047-6e87-4b5a-80a0-c91483bc5655)'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      az deployment group create --resource-group $(resourceGroupName) \
         --template-file $(templateFile) \
         --parameters webAppName=$(webAppName)